---
all:
  children:
    cisco:
      hosts:
        router01:
          ansible_host: 192.168.51.2
          hostname: RT-C1841
      vars:
        ansible_network_os: ios
        ansible_connection: network_cli
