---
- name: nftables - config
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
  notify: nftables

- name: nftables - enable
  ansible.builtin.service:
    name: nftables.service
    enabled: true
  notify: nftables