---
# basic system configuration
hostname: RT-C1841
domain_name: kamiya.local


# basic interface configuration
FE_interfaces:
  - name: FastEthernet0/0
    description: Connected to Internet
    enabled: yes
    duplex: auto
    speed: auto
  - name: FastEthernet0/1
    description: ""
    enabled: no
    duplex: auto
    speed: auto
SE_interfaces:
  - name: Serial0/0/0
    description: ""
    enabled: no
  - name: Serial0/0/1
    description: ""
    enabled: no


# L3 interface configuration
L3_interfaces:
  - name: FastEthernet0/0
    ipv4_address: 192.168.51.2/24


# clock configuration - ntp
ntp_server: 133.243.238.164


# archive configuration
tftp_server: 192.168.51.10


# logging configuration
syslog_server: 192.168.51.10
syslog_facility: local0


# snmp configuration
snmp_community: public


# routing configuration - default route
next_hop_router: 192.168.51.254


# banner configuration - login
banner_text: |
  ###################################################################
  ##########  Unauthorized access is strictly prohibited.  ##########
  ###################################################################