---
- name: cisco - archive
  cisco.ios.ios_config:
    lines:
      - "path tftp://{{ tftp_server }}/$h-$t.cfg"
      - write-memory
    parents:
      - archive
  notify: copy_run_start
  when: inventory_hostname in groups["cisco"]