---
- name: line - console
  cisco.ios.ios_config:
    lines:
      - exec-timeout 0 0
      - logging synchronous
    parents:
      - line con 0
  notify: copy_run_start
  tags: line

- name: line - aux
  cisco.ios.ios_config:
    lines: []
    parents:
      - line aux 0
  notify: copy_run_start
  tags: line

- name: line - vty
  cisco.ios.ios_config:
    lines:
      - exec-timeout 0 0
      - logging synchronous
      - transport input ssh
    parents:
      - line vty 0 4
  notify: copy_run_start
  tags: line