---
- name: cisco - logging - remote logging
  cisco.ios.ios_logging:
    dest: host
    name: "{{ syslog_server }}"
    facility: "{{ syslog_facility }}"
    state: present
  notify: copy_run_start
  when: inventory_hostname in groups["cisco"]
  changed_when: false  # なぜか毎回changedになるため

- name: cisco - logging - console logging
  cisco.ios.ios_logging:
    dest: console
    state: absent
  notify: copy_run_start
  when: inventory_hostname in groups["cisco"]