---
- ansible.builtin.import_tasks:
    file: basic.yml
- ansible.builtin.import_tasks:
    file: service.yml
- ansible.builtin.import_tasks:
    file: basic_interface.yml
- ansible.builtin.import_tasks:
    file: l3_interface.yml
- ansible.builtin.import_tasks:
    file: line.yml
- ansible.builtin.import_tasks:
    file: clock.yml
- ansible.builtin.import_tasks:
    file: archive.yml
- ansible.builtin.import_tasks:
    file: logging.yml
- ansible.builtin.import_tasks:
    file: snmp.yml
- ansible.builtin.import_tasks:
    file: routing.yml
- ansible.builtin.import_tasks:
    file: security.yml
- ansible.builtin.import_tasks:
    file: banner.yml