---
- name: cisco - routing - default route
  cisco.ios.ios_static_routes:
    config:
      - address_families:
          - afi: ipv4
            routes:
            - dest: 0.0.0.0/0
              next_hops:
                - forward_router_address: "{{ next_hop_router }}"
    state: merged
  notify: copy_run_start
  when: inventory_hostname in groups["cisco"]