---
- name: security - disable http server
  cisco.ios.ios_config:
    lines:
      - no ip http server
      - no ip http secure-server
  notify: copy_run_start
  tags: security

- name: security - disable SSHv1
  cisco.ios.ios_config:
    lines:
      - ip ssh version 2
  notify: copy_run_start
  tags: security

- name: security - AAA
  cisco.ios.ios_config:
    lines:
      - aaa new-model
      - aaa authentication login default local
      - aaa authorization console
      - aaa authorization exec default local
  notify: copy_run_start
  tags: security