---
- name: service
  cisco.ios.ios_config:
    lines:
      - service timestamps debug datetime msec localtime show-timezone
      - service timestamps log datetime msec localtime show-timezone
      - service password-encryption
  notify: copy_run_start